language: shell

os: windows

env:
  global:
    - VERSION=1.6.2
script:
  - choco pack --version $VERSION

before_deploy:
  - choco apikey --key $CHOCO_KEY --source "https://push.chocolatey.org/"

deploy:
  skip_cleanup: true
  provider: script
  script: choco push podman-cli.$VERSION.nupkg
  on:
    branch: master
